# yaml-language-server: $schema=https://raw.githubusercontent.com/bowlingx/super-release/main/schema.json
# super-release releases itself

branches:
  - main
  - master

tag_format: "v{version}"

plugins:
  - name: changelog
  - name: npm
    options:
      provenance: true
  - name: exec
    options:
      prepare_cmd: "sed -i'' -e 's/^version = .*/version = \"{version}\"/' Cargo.toml"
  - name: git-commit
    options:
      message: "chore(release): {releases} [skip ci]"
  - name: git-tag
